<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Super Admin',
                'email' => 'superadmin@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2022-01-28 15:16:30',
                'password' => '$2y$10$3Pd9a30Qjpl6OuNT3PcNoOONYlH/wRee5u3gJYaIVQ253pkmeJE6u',
            'profile_image_path' => '/profile_images/1690905720download (2).jpeg',
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => NULL,
                'updated_at' => '2023-08-03 11:43:37',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Jack Deen',
                'email' => 'jack@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-01 16:54:49',
                'password' => '$2y$10$pl5t8Z/NHRS3OFgs6IOQyu6aFCYDP66/gUHCnGo4KaE7LAgu6WaRO',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-01 16:54:49',
                'updated_at' => '2023-08-01 16:54:49',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'John Doe',
                'email' => 'john@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-03 15:45:50',
                'password' => '$2y$10$7Cf/DNx3d2xlgBPVXC2Z9.33L4jv0XKBfETYpfiRbwNx.QbrIzhiO',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-03 15:45:50',
                'updated_at' => '2023-08-03 15:45:50',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Ahsan Mono',
                'email' => 'ahsan.mono@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-03 15:51:33',
                'password' => '$2y$10$veRZAJvI0xmMXiUhA2LIlevByepZFlOVBjK2jAAPgKXZ4Gf0tbWyu',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-03 15:51:33',
                'updated_at' => '2023-08-03 15:51:33',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Ana mark',
                'email' => 'anamark@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-04 13:47:33',
                'password' => '$2y$10$qz/nF3ISDrIA9oGIpuCPdOSKgXSgvErCmBC56PUzW4G/gPwSVogiy',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-04 13:47:33',
                'updated_at' => '2023-08-04 13:47:33',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Oliver Mercer',
                'email' => 'olivermercer@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:28:59',
                'password' => '$2y$10$GcdUe0prnchGgY0ZSvt6V.8jdifuDymA9ZTbX4ajurmHGMf06.9Ka',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:28:59',
                'updated_at' => '2023-08-07 13:28:59',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Oliver Mercer',
                'email' => 'olivermercer@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:28:59',
                'password' => '$2y$10$8ovhCYbqs0jFgwvZNKFAG.ct2gD.3pWiNo6.ArqlwnCn8.RmWvMAO',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:28:59',
                'updated_at' => '2023-08-07 13:28:59',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Oliver Mercer',
                'email' => 'olivermercer@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:28:59',
                'password' => '$2y$10$K3vcFREuPirh6sMxCEa7FuorjuyoFeLVadJKOiR1KNHuefD7Uy1Q6',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:28:59',
                'updated_at' => '2023-08-07 13:28:59',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Oliver Mercer',
                'email' => 'olivermercer@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:28:59',
                'password' => '$2y$10$2Ra4YbSdkjNAcqBZ4i9YM.4iEJvf2nYybUhTpGnxeVYINVriHwnFa',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:28:59',
                'updated_at' => '2023-08-07 13:28:59',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Daniel Bennett',
                'email' => 'danielbennett@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:39:55',
                'password' => '$2y$10$gpRnCFrNYCCsz1N0oHrNMOnrLsEsfanEpm1oR1lEmnydbhTQriJfG',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:39:55',
                'updated_at' => '2023-08-07 13:39:55',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Amelia Justice',
                'email' => 'ameliajustice@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:54:13',
                'password' => '$2y$10$C09hyTponoaYsprV07hhgOQsBGq/G8F6Dm5uXa8bgs25hx.FX3cma',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:54:13',
                'updated_at' => '2023-08-07 13:54:13',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Amelia Justice',
                'email' => 'ameliajustice@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 13:54:13',
                'password' => '$2y$10$qAgez6N.evuPIlem7v3FlucysYwHZ8UE0mP6HRDTAt2TPq3X6YAQq',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 13:54:13',
                'updated_at' => '2023-08-07 13:54:13',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Thomas Bradford',
                'email' => 'thomasbradford@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 14:02:54',
                'password' => '$2y$10$.ryUIeqJhmDlL3uQFoz3kuT3aSEKUejAjP6TwrLaGeQDUBsU6mogS',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 14:02:54',
                'updated_at' => '2023-08-07 14:02:54',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Victoria Whitman',
                'email' => 'victoriawhitman@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 14:18:52',
                'password' => '$2y$10$wMuasJh04ASeaIFtreQiYOrswDQQa3QTX7knkakI/uCfgIjQ6zVeq',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 14:18:52',
                'updated_at' => '2023-08-07 14:18:52',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'James Thornton',
                'email' => 'jamesthornton@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 14:54:38',
                'password' => '$2y$10$tVCNgJIj9ujyjbnrga2pA.NM4mykULDg.JybWDxnxkt0.NTxNhGKG',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 14:54:38',
                'updated_at' => '2023-08-07 14:54:38',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Sophia Lancaster',
                'email' => 'sophialancaster@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 15:00:10',
                'password' => '$2y$10$lQhvKdq389hyp3.ndF82G.SA0hJotsSXOk27CBc9pjwRmC2yajl9C',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 15:00:10',
                'updated_at' => '2023-08-07 15:00:10',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Isabella Carrington',
                'email' => 'isabellacarrington@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-07 16:50:34',
                'password' => '$2y$10$5IyULRvJS69N/PTj2x4uOuZKS9pCXWjucSHOnloY0n.jthGFyWIVK',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-07 16:50:34',
                'updated_at' => '2023-08-07 16:50:34',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'adam shaw',
                'email' => 'adamshaw@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-09 09:16:12',
                'password' => '$2y$10$nVdhR0szeB7ztcSEPtuQDuFelvuITJfEouRKHGSr38msshQyzNRaK',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-09 09:16:11',
                'updated_at' => '2023-08-09 09:16:12',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'mono 1',
                'email' => 'mono@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-08-09 11:58:55',
                'password' => '$2y$10$skYkB8nrIp/OWLUUaqJnsu60zvk0iue0l4b0ug093gALcKR3oL5vm',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-08-09 11:58:55',
                'updated_at' => '2023-08-09 11:58:55',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Dean Jhon',
                'email' => 'dean@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-09-27 10:57:37',
                'password' => '$2y$10$eeq.1JEF4rj2o3PHEidN1uGNDHfTEM.LYhPnUTIMEVeWSxYpCBrpe',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-09-27 10:57:37',
                'updated_at' => '2023-09-27 10:57:37',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Jhon Dave',
                'email' => 'dave@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-09-27 11:57:09',
                'password' => '$2y$10$7Xj1s9D8COFhaNce5RdqdeBrXEfnj/X97Ro8X3QutzuPXDSd1278G',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-09-27 11:57:09',
                'updated_at' => '2023-09-27 11:57:09',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'john wick',
                'email' => 'johnwick@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-09-27 15:52:55',
                'password' => '$2y$10$oveJx77Vnz7FWfoEdyNLe.N/Hgu686jxU65OGY9deOJN6nVHUQiCu',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-09-27 15:52:55',
                'updated_at' => '2023-09-27 15:52:55',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Trendingadvisor Law agency',
                'email' => 'info@trendingadvisor.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-03 16:40:32',
                'password' => '$2y$10$/QFhRdu.iWaBFYxDX2htp.R9ioQ0Gwt5a.8C61Qq/wZBN7bZGSaEK',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-03 16:40:32',
                'updated_at' => '2023-10-03 16:40:32',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'muzamil younas',
                'email' => 'mistermuzammilyounas@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-04 16:54:09',
                'password' => '$2y$10$zl7PoTXNOkVhkYSfN98YEOSOyxICsTRY/3yxHoX0HSg228cszzyva',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-04 16:54:09',
                'updated_at' => '2023-10-04 16:55:43',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Cooper Hughes Law',
                'email' => 'Cooper@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-05 16:50:42',
                'password' => '$2y$10$FN4rLtkF.4eEZXBAz6E/jeRj72KY1k/LuEbl51FKMR4zX7Ce0CfP6',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-05 16:50:42',
                'updated_at' => '2023-10-05 16:50:42',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Daniel Mitchell',
                'email' => 'DanielMitchell@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-04 23:09:39',
                'password' => '$2y$10$Ib7moxFwGR7g4NBMwaYVu.FkKR4nD.lpGfAWJi5/MloJJT0UAoMM2',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-05 17:52:54',
                'updated_at' => '2023-10-05 17:52:54',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Emily Davis',
                'email' => 'emily.davis@damylawfirm.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-05 19:10:50',
                'password' => '$2y$10$xID7H0vjOj9FcBaSxbOEzO0XHN7.6l/hOgiCwkJr0rwGcFHPzU7g6',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-05 19:10:50',
                'updated_at' => '2023-10-05 19:10:50',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Sarah Johnson',
                'email' => 'sarah.johnson@example.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-05 00:56:11',
                'password' => '$2y$10$RB52bXJhhppquqqysrdnjOKTBq8rdUA9fnJIjCU3qMs23Ejs8uZ/a',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-05 19:41:45',
                'updated_at' => '2023-10-05 19:41:45',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Brown David',
                'email' => 'david.brown@example.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-05 00:56:16',
                'password' => '$2y$10$BN294RbOB05xuMDo1qn94e6fgltsPsMgUrfmOeYifR5Uq1haxvDRi',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-05 19:45:20',
                'updated_at' => '2023-10-05 19:45:20',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Benjamin Crawford',
                'email' => 'Benjamin@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-06 00:03:51',
                'password' => '$2y$10$ShbXfY5TgIHbpnInN.Q0j.0Ipu6pGqVspG4Xhl9bXMqd39XsDQNIW',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-06 18:20:52',
                'updated_at' => '2023-10-06 18:20:52',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'David Thompson',
                'email' => 'David@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-05 00:03:56',
                'password' => '$2y$10$HeriP.XxlLkPRH9I85RmUerKBsocwiNlJ8HL2bB1IvDasPbMSZlUO',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-06 18:27:18',
                'updated_at' => '2023-10-06 18:27:18',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Jonathan Baker',
                'email' => 'Jonathan@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-06 00:04:01',
                'password' => '$2y$10$Kp.03/wCqm9ESFKxgajIt.evcdAcfXfq9Y6XbCYTDLP8dKc3w5UTG',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-06 18:31:55',
                'updated_at' => '2023-10-06 18:31:55',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Sophia Martinez',
                'email' => 'Sophia@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-06 00:04:04',
                'password' => '$2y$10$bVH3EfxwnfJg6pKledh7RO.8YIdgDRt9iWHxWUyZxKPM.u2lJS4o.',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-06 18:43:04',
                'updated_at' => '2023-10-06 18:43:04',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Zoe Anderson',
                'email' => 'Zoe@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-06 00:04:07',
                'password' => '$2y$10$80HkCS82/h9im8dHU.q2rOD.Rqqc7idcGojBi1RGbQI2qx2aaFowe',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-06 18:46:21',
                'updated_at' => '2023-10-06 18:46:21',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Jessica Taylor',
                'email' => 'jessica@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-03 20:55:56',
                'password' => '$2y$10$n90aB7asRoi1SIGJrKmTEu2xcWzsd8IcdeyyV8w6rHECUN8dZ2OV6',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-09 15:38:02',
                'updated_at' => '2023-10-09 15:38:02',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Laura Parker',
                'email' => 'laura@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-03 20:55:59',
                'password' => '$2y$10$HTuESKBzqKKA8KLxxraDquCgxy6EmPKH41FLU4/sYZuIPEx0kCNzK',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-09 15:41:32',
                'updated_at' => '2023-10-09 15:41:32',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'mark jhon',
                'email' => 'markjhon@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-12 12:50:15',
                'password' => '$2y$10$XpEM/MNnpgu1xCnYiGcfpOHj2YWX9WeEHumKKtw6OpX.2geNipE66',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-12 12:50:15',
                'updated_at' => '2023-10-12 12:50:15',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'jimmy m',
                'email' => 'jimmy@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-23 15:52:20',
                'password' => '$2y$10$Ql3fTN6zgZ/TU0IUnFD3auDyrMcf5CLuw8jQ9CLOcu3K3cSqwqMwS',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-23 15:52:20',
                'updated_at' => '2023-10-23 15:52:20',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Jackson Carter',
                'email' => 'jackson@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-25 22:40:13',
                'password' => '$2y$10$/o8W4UzrKRnqWX1Jvk3ZLeTA1AkJwV6OkReeKfOSg1Q/MlvOF/Qj2',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-23 17:37:04',
                'updated_at' => '2023-10-23 17:37:04',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'name' => 'Faizan Fazal',
                'email' => 'subhansheikh12212@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-10-26 19:59:21',
                'password' => '$2y$10$Xh6BjyInnqXo1Pme5fTujOgLh89V3TUj6gtEphfHeg82GdADSATga',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-10-26 19:59:21',
                'updated_at' => '2023-10-26 19:59:21',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 43,
                'name' => 'james Andersion',
                'email' => 'james@gmail.com',
                'is_active' => 1,
                'country_id' => NULL,
                'email_verified_at' => '2023-11-03 16:19:51',
                'password' => '$2y$10$q/v89vChmN5O77rA53Pc1.gfJw7G3xJ/hKicsc6T.1wIxWpZJ6ZA.',
                'profile_image_path' => NULL,
                'remember_token' => NULL,
                'is_two_factor_enabled' => 0,
                'two_factor_verification_code' => NULL,
                'two_factor_verification_expiry' => NULL,
                'password_last_changed' => NULL,
                'created_at' => '2023-11-03 16:19:51',
                'updated_at' => '2023-11-03 16:19:51',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}