services:
  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    restart: always
    networks:
      - app-tier

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   restart: always
  #   networks:
  #     - app-tier
  #   depends_on:
  #     - php-fpm
  #   volumes:
  #     - ./source/stake:/var/www/html
  #     - ./nginx/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
  #     - ./certs:/etc/ssl/certs
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./nginx/snippets:/etc/nginx/snippets
  #     - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
  #     - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
  #   ports:
  #     - "80:80"
  #     - "443:443"

  redis:
    image: bitnami/redis:7.2
    networks:
      - app-tier
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      REDIS_PASSWORD: LcbThvQKn7NlTsM
    ports:
      - '6379:6379'
    # volumes:
    #   - 'redis_data:/bitnami/redis/data'

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: x7mi2RtwfqT1ZC8
      MYSQL_DATABASE: lawyers
      MYSQL_USER: lawyers
      MYSQL_PASSWORD: x7mi2RtwfqT1ZC8
    # volumes:
    #   - mysql_data:/var/lib/mysql

networks:
  app-tier:
    driver: bridge

# volumes:
#   redis_data:
#     driver: local
